<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        $nisList = [
            // X DKV 1
            '00833',
            '00834',
            '00835',
            '00836',
            '00837',
            '00838',
            '00839',
            '00840',
            '00841',
            '00842',
            '00843',
            '00844',
            '00845',
            '00846',
            '00847',
            '00848',
            '00849',
            '00850',
            '00851',
            '00852',
            '00853',
            '00854',
            '00855',
            '00856',
            '00857',
            '00858',
            '00859',
            '00860',
            '00861',
            '00862',
            '00863',
            '00864',
            '00865',
            '00866',
            '00867',

            // X DKV 2
            '00868',
            '00869',
            '00870',
            '00871',
            '00872',
            '00873',
            '00874',
            '00875',
            '00876',
            '00877',
            '00878',
            '00879',
            '00880',
            '00881',
            '00882',
            '00883',
            '00884',
            '00885',
            '00886',
            '00887',
            '00888',
            '00889',
            '00890',
            '00891',
            '00892',
            '00893',
            '00894',
            '00895',
            '00896',
            '00897',
            '00898',
            '00899',
            '00900',
            '00901',
            '00902',

            // X PPLG 1
            '00761',
            '00762',
            '00763',
            '00764',
            '00765',
            '00766',
            '00767',
            '00768',
            '00769',
            '00770',
            '00771',
            '00772',
            '00773',
            '00774',
            '00775',
            '00776',
            '00777',
            '00778',
            '00779',
            '00780',
            '00781',
            '00782',
            '00783',
            '00784',
            '00785',
            '00786',
            '00787',
            '00788',
            '00789',
            '00790',
            '00791',
            '00792',
            '00793',
            '00794',
            '00795',
            '00796',

            // X PPLG 2
            '00797',
            '00798',
            '00799',
            '00800',
            '00801',
            '00802',
            '00803',
            '00804',
            '00805',
            '00806',
            '00807',
            '00808',
            '00809',
            '00810',
            '00811',
            '00812',
            '00813',
            '00814',
            '00815',
            '00816',
            '00817',
            '00818',
            '00819',
            '00820',
            '00821',
            '00822',
            '00823',
            '00824',
            '00825',
            '00826',
            '00827',
            '00828',
            '00829',
            '00830',
            '00831',
            '00832',

            // X BCF 1
            '00903',
            '00904',
            '00905',
            '00906',
            '00907',
            '00908',
            '00909',
            '00910',
            '00911',
            '00912',
            '00913',
            '00914',
            '00915',
            '00916',
            '00917',
            '00918',
            '00919',
            '00920',
            '00921',
            '00922',
            '00923',
            '00924',
            '00925',
            '00926',
            '00927',
            '00928',
            '00929',
            '00930',
            '00931',
            '00932',
            '00933',
            '00934',
            '00935',
            '00936',
            '00937',

            // X BCF 2
            '00938',
            '00939',
            '00940',
            '00941',
            '00942',
            '00943',
            '00944',
            '00945',
            '00946',
            '00947',
            '00948',
            '00949',
            '00950',
            '00951',
            '00952',
            '00953',
            '00954',
            '00955',
            '00956',
            '00957',
            '00958',
            '00959',
            '00960',
            '00961',
            '00962',
            '00963',
            '00964',
            '00965',
            '00966',
            '00967',
            '00968',
            '00969',
            '00970',
            '00971',
            '00972',

            // XI PPLG 1
            '00579',
            '00584',
            '00544',
            '00546',
            '00548',
            '00549',
            '00550',
            '00551',
            '00552',
            '00586',
            '00554',
            '00555',
            '00556',
            '00590',
            '00559',
            '00562',
            '00563',
            '00564',
            '00566',
            '00595',
            '00599',
            '00567',
            '00568',
            '00601',
            '00571',
            '00572',
            '00573',
            '00574',
            '00575',
            '00576',
            '00610',
            '00577',
            '00612',
            '00613',
            '00578',

            // XI PPLG 2
            '00580',
            '00581',
            '00543',
            '00582',
            '00583',
            '00585',
            '00553',
            '00587',
            '00588',
            '00589',
            '00557',
            '00591',
            '00592',
            '00558',
            '00560',
            '00593',
            '00561',
            '00594',
            '00565',
            '00596',
            '00597',
            '00598',
            '00600',
            '00602',
            '00569',
            '00603',
            '00570',
            '00604',
            '00605',
            '00606',
            '00607',
            '00608',
            '00609',
            '00611',
            '00614',

            // XI DKV 1
            '00615',
            '00616',
            '00617',
            '00618',
            '00619',
            '00620',
            '00621',
            '00622',
            '00623',
            '00624',
            '00625',
            '00626',
            '00627',
            '00628',
            '00629',
            '00630',
            '00631',
            '00632',
            '00633',
            '00634',
            '00635',
            '00636',
            '00637',
            '00638',
            '00639',
            '00640',
            '00641',
            '00642',
            '00643',
            '00644',
            '00645',
            '00646',
            '00647',
            '00649',
            '00650',

            // XI DKV 2
            '00651',
            '00652',
            '00653',
            '00654',
            '00655',
            '00656',
            '00657',
            '00658',
            '00659',
            '00660',
            '00661',
            '00662',
            '00663',
            '00664',
            '00665',
            '00666',
            '00667',
            '00668',
            '00669',
            '00670',
            '00671',
            '00672',
            '00673',
            '00674',
            '00675',
            '00676',
            '00677',
            '00678',
            '00679',
            '00680',
            '00681',
            '00682',
            '00683',
            '00684',
            '00685',
            '00686',

            // XI BCF 1
            '00687',
            '00689',
            '00690',
            '00725',
            '00691',
            '00727',
            '00728',
            '00692',
            '00693',
            '00694',
            '00698',
            '00700',
            '00701',
            '00702',
            '00705',
            '00708',
            '00742',
            '00709',
            '00743',
            '00710',
            '00745',
            '00746',
            '00713',
            '00747',
            '00748',
            '00749',
            '00750',
            '00752',
            '00753',
            '00717',
            '00718',
            '00719',
            '00755',
            '00756',
            '00722',

            // XI BCF 2
            '00688',
            '00723',
            '00724',
            '00726',
            '00729',
            '00730',
            '00731',
            '00732',
            '00695',
            '00733',
            '00734',
            '00696',
            '00697',
            '00735',
            '00699',
            '00736',
            '00737',
            '00703',
            '00704',
            '00738',
            '00740',
            '00741',
            '00706',
            '00707',
            '00744',
            '00711',
            '00712',
            '00714',
            '00715',
            '00716',
            '00751',
            '00754',
            '00720',
            '00721',
            '00757',

            // XII PPLG 1

            '00324',
            '00325',
            '00361',
            '00326',
            '00362',
            '00328',
            '00365',
            '00330',
            '00366',
            '00331',
            '00369',
            '00370',
            '00371',
            '00334',
            '00335',
            '00377',
            '00381',
            '00338',
            '00759',
            '00340',
            '00383',
            '00341',
            '00345',
            '00346',
            '00350',
            '00388',
            '00389',
            '00390',
            '00353',
            '00354',
            '00355',
            '00391',
            '00392',
            '00358',
            '00393',

            // XII PPLG 2
            '00758',
            '00360',
            '00539',
            '00327',
            '00363',
            '00364',
            '00329',
            '00367',
            '00368',
            '00332',
            '00333',
            '00372',
            '00373',
            '00374',
            '00375',
            '00336',
            '00376',
            '00337',
            '00541',
            '00378',
            '00540',
            '00339',
            '00382',
            '00384',
            '00343',
            '00385',
            '00347',
            '00386',
            '00348',
            '00349',
            '00387',
            '00351',
            '00352',
            '00357',
            '00359',
            '00394',

            // XII DKV 1
            '00395',
            '00396',
            '00397',
            '00398',
            '00399',
            '00401',
            '00402',
            '00437',
            '00404',
            '00405',
            '00406',
            '00409',
            '00442',
            '00412',
            '00542',
            '00414',
            '00444',
            '00446',
            '00416',
            '00448',
            '00418',
            '00450',
            '00451',
            '00420',
            '00454',
            '00421',
            '00422',
            '00423',
            '00424',
            '00425',
            '00426',
            '00427',
            '00461',
            '00463',
            '00465',
            '00466',

            // XII DKV 2
            '00431',
            '00400',
            '00432',
            '00433',
            '00434',
            '00435',
            '00436',
            '00438',
            '00403',
            '00439',
            '00407',
            '00408',
            '00410',
            '00441',
            '00411',
            '00443',
            '00413',
            '00445',
            '00447',
            '00415',
            '00417',
            '00449',
            '00419',
            '00453',
            '00455',
            '00456',
            '00457',
            '00458',
            '00459',
            '00460',
            '00428',
            '00429',
            '00430',
            '00462',
            '00464',

            // XII BCF 1
            '00468',
            '00469',
            '00470',
            '00472',
            '00473',
            '00475',
            '00508',
            '00511',
            '00479',
            '00513',
            '00481',
            '00515',
            '00483',
            '00485',
            '00486',
            '00518',
            '00489',
            '00490',
            '00520',
            '00521',
            '00492',
            '00523',
            '00493',
            '00526',
            '00494',
            '00495',
            '00527',
            '00498',
            '00530',
            '00499',
            '00500',
            '00532',
            '00502',
            '00537',
            '00467',
            '00471',
            '00474',
            '00503',
            '00504',
            '00505',
            '00476',
            '00477',
            '00506',
            '00509',
            '00510',
            '00480',
            '00512',
            '00482',
            '00484',
            '00487',
            '00517',
            '00488',
            '00491',
            '00519',
            '00522',
            '00524',
            '00525',
            '00496',
            '00497',
            '00528',
            '00529',
            '00531',
            '00533',
            '00501',
            '00535',
            '00536',
            '00538',

            // XIII BCF 1
            '00286',
            '00287',
            '00288',
            '00289',
            '00290',
            '00291',
            '00292',
            '00293',
            '00294',
            '00295',
            '00296',
            '00297',
            '00298',
            '00299',
            '00300',
            '00301',
            '00302',
            '00303',
            '00304',
            '00305',
            '00306',
            '00307',
            '00308',
            '00309',
            '00310',
            '00311',
            '00312',
            '00313',
            '00314',
            '00316',
            '00317',
            '00318',
            '00319',
            '00320',


            // GURU / PENGURUS SEKOLAH
            '001',
            '002',
            '003',
            '004',
            '005',
            '006',
            '007',
            '008',
            '009',
            '010',
            '011',
            '012',
            '013',
            '014',
            '015',
            '016',
            '017',
            '018',
            '019',
            '020',
            '021',
            '022',
            '023',
            '024',
            '025',
            '026',
            '027',



            // ADMIN ADMIN ADMIN
            '656565'
        ];

        $usernames = [
            // X DKV 1
            'ABDURRAHMAN ZENSMITH',
            'AFDHOLUL ICHTISOR HASYIM',
            'ANGGA NOVIAN PUTRA',
            'ARSILA AULIA AZIS',
            'AURA HERNA ANGGRAENI',
            'AZ ZAHRA',
            'BAGAS IKHSAN ALVIANO SASTRO P',
            'BELLA ANINDYA JASMINE',
            'CARISSA APRILLIA RACHMAT',
            'FALISA BIA AMANDA',
            'FATTAH RAHMATULLAH',
            'FAZLI EHSAN ZAQUAN',
            'HERLAMBANG TRI PRIMANDIKA',
            'ISMA SYAFA ALFATHIRA',
            'JIHAN CLARISSA SANJAYA',
            'KEISHA ZALVA SUWITO',
            'KEYNARA ALVISHA FERDIAN',
            'KIRANA BINTANG AULYA',
            'LAISHA NUR AULIA QOLBI',
            'LETVI SUKMA ALGI FAHRI',
            'LIANI',
            'MOZZA AURELI SUHERLI',
            'MUHAMAD IKHSAN JULIANTO',
            'MUHAMMAD FITRAH MAULANA',
            'MUHAMMAD KHOTIB IBNU MAJID',
            'NAYLA AUDRIA HAIKAL',
            'NEILA ARTIKA PUTRI',
            'RANA MAYLINDA',
            'RIZKY PUTRA PRATAMA SAMAGITA',
            'SHAFA SALSABILA',
            'SHINTIA WATI',
            'VELECIA GABBYOLA RUUS',
            'WENONA ANANDYA KEANDRI',
            'ZACHRY ORVA MAURINO',
            'ZAKITA PUTRI AL QIBTIA',

            // X DKV 2
            'AFIYO PUTRI ANAMI',
            'AHMAD NUR YUSUF',
            'AHMAD RIFIAR',
            'AMALIA RIZKY',
            'AYU MAULIDA',
            'BILQIS MAULIDA SHAFIRA',
            'CATHARINA ANGELIQUE WEA WIJAYA',
            'DAFITA GERISH RUMAHORBO',
            'DAWA IBRAHIM',
            'FAKHRI ZAIDAN',
            'FATHAN KHAIRANI SHABRU MUSTOFA',
            'FIRDA FATHIAH ADDYNI',
            'GADIS SEKAR ARUM',
            'HANNA AULIA ZAHRA',
            'IBADURRAHMAN SHIDDIQ',
            'KEIYLA NAYSILA PUTRI',
            'KHAIRUNNISA DWI SUGATI',
            'MAHARANI',
            'MAULIDIYAH AZIZAH',
            'MOHAMAD HARZAN ZAFRAN',
            'MUHAMMAD AFFARIZI',
            'MUHAMMAD FAIZ ATHAYA',
            'MUHAMMAD RAFLI',
            'MUHAMMAD REIHAN',
            'NAJWA LATHIFAH AZZAHRA',
            'NIHAYATU ZAHIRA',
            'RAFIF ARYA DINATA',
            'RAFILAH RIZKI MAULIDA',
            'REVAL ARYA DINATA',
            'RIFQAH HANA MUTIARA',
            'SYIFA ZAHROTUN NISA',
            'WULANDARI NURUL AZRA',
            'ZAHRA KHUMAIROH',
            'ZEECHRA RACHEL SIHOMBING',
            'ZIQRA JAVAS PRAYATA',

            // X PPLG 1
            'ACHMAD SAKHI HAMZAH',
            'ADELIA PUTRI RAMADHANI',
            'ADI ARRASYID',
            'ALIFIA RIFQOH IFAWATI',
            'ALVIAN ANANTA DEWA',
            'ARAHSTI PIRNI',
            'AULIA FATIA SAFITRI',
            'AULYA NASTYA RIDWAN',
            'BAGAS ADI PRIYANTO',
            'CHARISSA TARA FAJRIYATI',
            'DAFFA ZAIDAN ABDURRAHMAN',
            'DZAKWAN MAULANA HAFIZH',
            'DZAKWAN YUAR ROFIIF',
            'FACHRI PUTRA ADMA',
            'FADHIL TRI YONISRA',
            'FARID IMANSYAH',
            'GIBRAN KHARISMA JIBRIL',
            'HANIF ABDURRAHMAN',
            'JELITA RAMADHANI',
            'MIKHAEL ADRIAN',
            'MUHAMAD VINZA SANZAMIL',
            'MUHAMMAD DWI FIKRY FIRMANSYAH',
            'MUHAMMAD DZAKY RIZQULLAH',
            'MUHAMMAD NEIL KENZI',
            'MUHAMMAD RAIS ASSHADIQ',
            'MUHAMMAD RIZQI AKBAR',
            'QUEEN ZAHYAN UFAIRAH GUNAWAN',
            'RAYHAN PUTRA SIGIT',
            'SAFHIRA ARDELIA PRAMESTY',
            'SALWA NUR SA\'ADAH',
            'SUKMA ANDJANI',
            'SYHAILAH MUNIROH',
            'TRINANDA KIRANA',
            'YASMIN FEBRIANTI',
            'ZAHRA AULIA PUTRI',
            'ZASKIA SALSABILA',

            // X PPLG 2
            'AJDA NAILLA SYAFIQAH',
            'ALIYAH SALSABILA',
            'APPUPAH SYA\'BANYAH',
            'AQUILA MAULIDA RISMA',
            'ARKAN NAUFAL PUTU HARDJONO',
            'ATHALLAH MALIK PRAYITNO',
            'AUFA ATTHALLAH NUR MUHAMMAD ILYASA LUBIS',
            'AURELL MARYCE INARKOMBU',
            'AURORA EKA MARPAUNG',
            'BRIAN RALPHAEL TUMIWA',
            'DESTA DWI NATTA',
            'DIAN SAFITRI',
            'ERIKA FITRIA',
            'FARAH AULIA',
            'FIFI AULIA',
            'GILANG FARREL RAJENDRA SUGIYANTO',
            'HUSEIN SYAHPUTRA',
            'IBRAHIM FIRDAUS',
            'KHANIZA IPAK QUINNYTA',
            'MILANI JANEETA AZALIA',
            'MUHAMMAD CHAIRUL ICHSAN',
            'MUHAMMAD HAZAMI IDRIS',
            'MUHAMMAD RAIHAN MAULIDDAN BUDIMAN',
            'MUHAMMAD ZOVANKA FADHILA',
            'NURAINI HANNY AZZAHRA',
            'PUTRA PRATAMA',
            'RIDHO TRI MAULANA',
            'RIZKI RIDHO ARFANDI',
            'SALMA UTAMI',
            'SASKIYA SYAFRINA',
            'SATRYA AUDIOSLAVE LIPENO',
            'SHALMA APRILIANI',
            'SITI NUR AISYAH',
            'SYALWA RIZKY HARYANTO',
            'YULIA RAHMAWATI',
            'ZHAFRAN ZAKA LINGGA',


            // X BCF 1
            'ACHMAD FAHREZY',
            'ADELINA NASUTION',
            'ADELIYA SETIAWAN',
            'ADISTY MAHARANI PUTRI DHINANTI',
            'AGNES SHEILA YANRI',
            'BINTANG PRATAMA RAFANO',
            'DINDA DAMAYRA',
            'DIVA ELLIKA',
            'EKA ADITYA',
            'ELVI NURAYYNI ANWAR',
            'ESTIRINO WIDYANTI',
            'FANY TRI UNTARI',
            'FIRSYA CHOIRUNISSAH',
            'FITRI ALMAQVIRA',
            'GISKA JOFISA',
            'HUTAMA MANDALA PUTRA',
            'INTAN NIA RIZKI',
            'KEYLA RINDA PUTRI',
            'KHAIRA NICHITA SYAHLA',
            'KIOSHI HAYFA RASHAD',
            'LUTVIA PURNAMASARI',
            'MOHAMAD NOORWAN',
            'MUHAMMAD RAMDAN SYAQRON',
            'MUSA MUSTINOVAN',
            'NAYLA AZZAHRA',
            'NAZIA IMELDA PRAMESTY',
            'NOVIA CAHAYA PUTRI',
            'NYI MAS ARUM',
            'PUTRI ADYSTI',
            'RORO CHEZHA NAYLA PUTRI',
            'SIVA CAHYA AULIA',
            'SYAHIRA KIRANY',
            'SYAKIRA SYIFA MAHARANI',
            'ZAHRA AMALIA',
            'ZIZA RAMADHANI',

            // X BCF 2
            'AISYAH RISTIANA AL MAQFIRA',
            'ALVIAH FAIRUS ZABADIE',
            'ANINDYA FATHIA SYAZA',
            'APRILIA DWI YANTHI',
            'ARZHAVIN IBNU PRIATHAMA',
            'AURA RACHELLAILLIA ARUAN',
            'BUMISARI',
            'CYNTHIA NATALI PERMATA PURBA',
            'DEVINDA MARCELA',
            'DIMAZ',
            'ELVINA RIZQY FADILAH',
            'ERNAH',
            'FITRIYAH RAHMADHANI',
            'HILWANA ZAFIRAH',
            'KEYURA ANAKYA MUKTI',
            'KHANZA AULIA PUTRI',
            'LARASATI',
            'MOHAMMAD HAYDAR ALI',
            'MUHAMMAD JAMI AL FAHRI',
            'MUHAMMAD RAFFI UD\'DIN',
            'NABIL RIFQI ARAHMAN',
            'NADILA AURA KASIH',
            'NAEYLA AININ DARWIN',
            'NAFILLAH NURHUWAIDA ALTHAAF',
            'NAJWA AZIZAH',
            'PUTRI NAYLA ZAHIIRA',
            'PUTRI RIANA',
            'REVAN AGUS SETIAWAN',
            'SABRINA BELLA PUTRI',
            'SEKAR ARUM HANDAYANI',
            'SEPTI CAHAYA RAMADANI',
            'SYARIFA FIRDA SALSABILA',
            'SYIFA MEIDYNA ALYA',
            'YOAN AHMAD PRATAMA',
            'ZAHRA NURDIANA',

            // XII PPLG 1
            'ADELIA NUR HIDAYAH',
            'ALFATTAH SABIL',
            'ALYA ATIQAH SALIMAH',
            'ANDIKA CAHYA RAHMAN',
            'AUDY NUR AFRINA',
            'AZMI RUGAYYAH',
            'CINTA AULIA HAPSARI',
            'DAVA ANDHIKA',
            'DZAKY RENDRA BARUNA BARLIANTO',
            'FATHAN AKBAR TRISTANTO',
            'GABY RIAKEL',
            'GITA NAFIZA DAWUD',
            'HAMKA HAMZAH HERMAWAN',
            'KEZIA AHMAD FAHREZI',
            'LAELATUL KHASANAH',
            'MUHAMAD FAREL KAMIL',
            'MUHAMMAD DENI UMARHADI',
            'MUHAMMAD DZIKRI ALFARIZI',
            'MUHAMMAD HAIKAL PUTRA YANDITA',
            'MUHAMMAD IBNU FAQIH',
            'MUHAMMAD ZUFAR MUNIF',
            'NASYA AULIA SAHIRA',
            'NOVRIKA RIONA',
            'OLIVIA PUTRI AGUSTINA NAINGGOLAN',
            'RAINA SHAVAIRA',
            'RANI NOVIANTI',
            'REIZA SYAIFUL AMAR',
            'SANDIKA HAFIIZH',
            'SUCI RAMADHANI DANTJIE',
            'SYAFIQ AHMAD HADZAMI',
            'TONY FELICIO FARREL',
            'TRI ANDIKA HANIF',
            'VIOLA',
            'WULAN LESTARI',
            'YEHEZKIEL RAINHEART MARIO SIHALOHO',

            // XII PPLG 2
            'ADINDA AYU RIZKY SUSANTI',
            'AGUNG LAZUWARDI',
            'AHMAD',
            'AHMAD HASAN PRIADI',
            'AHMAD ZIDAN ZACHRIANSYAH',
            'CHELFYA MEYLANY',
            'EPAN GUNAWAN',
            'GALIH AGENG PANGESTU',
            'HAFIZH PRATAMA',
            'HALIMATUS SADIAH DWI LESTARI',
            'HOIRUN NISA',
            'KHADAFI RAFA RAMADHAN',
            'KHURIN IN',
            'KIRANA PUTRI HIMAWAN',
            'MAULANA MUADZ AL BANTANI',
            'MIFTAH NAUFAL',
            'MUHAMAD ABIB MUBAROK',
            'MUHAMMAD DAFFA HAFIZH',
            'MUHAMMAD HADZAMI',
            'MUHAMMAD RAFFLI ARDITYA',
            'MUHAMMAD RANDU WEDYA RAIHAN KHAIRI',
            'MUHAMMAD RANU WIBOWO',
            'NADINDA NAJUWA',
            'PRADHITYA AZMI RAFIF',
            'PRINCESSIA AZZAHRA SYAMIAGUNG',
            'QAISYA AZAHRA',
            'RACHEL AULIA',
            'REVA AMELIA PUTRI',
            'RIZQI ADITYA SUMARDIANTO',
            'SAFFA AULIA ZAHRA',
            'SAZKIA MEILIYA ROSSA',
            'SETU AMMAR RERIYANSYAH',
            'STEVAN RIZKY AL-QARNI',
            'TRISTAN FAIZ ALTAMIS',
            'ZELFA ZAHIYA AGUSTINA',

            // XI DKV 1
            'ACHMAD FADLY',
            'ADIRA NAZLA ZAHIRA GUNAWAN',
            'ALIF PRADITYA KALA',
            'ANISA AURELLIA',
            'ASSEYKA FELLA ALAYA',
            'ATAYA RIZQULAH RAMADHANY',
            'CHICKA AMEL NAJLA',
            'DENTING MUSICA RAMADHANI',
            'DEVI SABRINA',
            'DIVANDRA ISLAMIA AZZAHRA',
            'FAIRUUZZIA AULIA FACHRIZAL',
            'FAJRIAN',
            'FAUZAN',
            'FIARISSA RAMANDA FIRDAUS',
            'HANIF BANIE FAIRUZ',
            'INDAH AINIYA PUSPA AYU',
            'INDIRA SALSABILLAH',
            'KAILA SYITA ROSYADI',
            'MUHAMMAD FADHIL RAMADHAN',
            'MUHAMMAD RIZKY ALFATIH',
            'MUTIARA NURHIDAYAH',
            'NAIRA MAULIDINA',
            'NOVAN ARIZKY PRATAMA',
            'NURYANTI YULIANA',
            'PUTRI LATHIFAH',
            'RAHMA DWI NOVIANTI',
            'RAIHAN ANGGORO SAFAR AL-HADI',
            'RIZKA PUTRI AL FITRAH',
            'RIZKY ATHALLAH HARRIS',
            'SAFIRA NUR ROHMAH',
            'SARAH NAILA RAIHANAH FAHMASHARI',
            'SETO TRI WICAKSONO',
            'SITTI CHOFIFAH',
            'SYAPUTRA DWI ANDIKA',
            'ZETAVA VEYLISTIA DEWI MULYO',

            // XI DKV 2
            'ALANSYAH FATAHIR RISQAN',
            'ANISA SAFIRA',
            'APRILLIA LISTIYA NINGSIH',
            'ARDY HAMDANI PUTRA',
            'AULIA YASMIN',
            'BILQIS SYIFA MALINDA',
            'CANTIKA AZZAHRA RIDHO',
            'DATHU MAESA AYU',
            'DIAS KIRANI',
            'DILA REVA INDRIYANI',
            'DWI ULFA ZAHRA',
            'FAAZA DWI RAHMA',
            'FATHUR AJIE PUTRA',
            'HAURA ZAHRATUS SYIFA',
            'HILMAN DARMAWAN',
            'IFFAH FITHRIYAH',
            'MINARTI RAHAYU',
            'MUHAMMAD ALFREIAN JANUAR PUTRA',
            'MUHAMMAD FACHRI ALDIANSYAH',
            'MUHAMMAD REVAN PRASETYA',
            'NAISY QOTHRATUN NADA',
            'NANDA TRI ANDIKA',
            'NATASYA AZAHRA',
            'NAUFAL AFKAR SAVARAZ',
            'NAZHWA ZAHIRA',
            'PUTRI SOLEHA APRIYANI',
            'RAISYAH FAHMA',
            'RAYSA NUR KAMILA',
            'RENO GUMELAR',
            'SADDAM ALI MUHAMMAD',
            'SURYA CINDAR BUMI',
            'SYARYFAH HADAWIYAH',
            'SYIFA AIRLIAGNI AURORA',
            'TANGGUH ONOMATUA HULU',
            'VEGA AGUNG SHAFIYYAH',
            'YOSIA DESENDO LALAMENTIK',

            // XI BCF 1
            'ACHMAD FATIH GHAISAN KURNIAWAN',
            'ANGGI NIRMALA',
            'ANISSA RAHMARANI PUTRI',
            'AQILAH',
            'ARDHY NUR ALIEF',
            'ATIRA SALSABILA',
            'AULIA APRIL MULIA',
            'AYESHA RAMADHANI',
            'BILQIS BUNGA AMELIA',
            'BUNGA LESTARI',
            'FABIO MALIKY',
            'FAUZIAH NUR RAHMADHINA',
            'HADIDAH HANDAYANI HIRLLY',
            'HAFUZA NAQUILA SASMITA',
            'KHOIRUL AZIZ',
            'MAGHFIRLINA ALIFAH APRILIANI',
            'MELDA DEVINA',
            'MOHAMMAD FASLI FADILLAH',
            'MUHAMMAD FAJRI JAJULI',
            'MUHAMMAD PASHA PUTRA',
            'NASYWA HAFIZ',
            'NAYLA PUTRI HERVIANSYAH',
            'NAZYA ZALZILAH SOLEHA',
            'NIKI AULIA INDRIYANI',
            'NOVELIA DAEFRIANA',
            'PUTRI SARAH',
            'RACHMAT KURNIAWAN WIBISONO',
            'RAFILA IZZATIN NISA',
            'RAHMAH AZZAHRAWATI',
            'RAYYA PUTRI RAMADANI',
            'RESTI ASTRIYANTI',
            'RIFDAH SALSABILA',
            'RIFKA SYAHLA ZAFIRA',
            'RIVAI MUNTASHIR',
            'TRISYA ROSHA CAPRISYA',

            // XI BCF 2
            'AFRILYA HANDAYANI',
            'AHLAN HABIBI',
            'ALYA FEBRIA AINI',
            'ARIKA SHAHIRA ALVIRANO',
            'AURELIA SAFIRA ANWAR',
            'AZRIEL ADISTY PRATAMA',
            'BIMA AKHBAR NGARESTHU',
            'BUNGA NATASYA PUTRI',
            'CANTIKA ELCYNTIA',
            'CARINA AGNES ARIANI DIRK',
            'DERA ARDINIA',
            'DIMAS',
            'DIYAH HUSNI HAVIVAH',
            'DZIMAR MAFAZA',
            'FAIRUZ FATHUR RAHMAN HIDAYAH',
            'FARRAS SAKHI AHMAD',
            'HALIMAH TUSSADIYAH',
            'INAYA KHAIRUNISA',
            'JELITA MAWAR',
            'KAELA DIVA KIRANA',
            'KEYZI FINIA SYABANI',
            'LATIFATUL AULIA',
            'LIANA SYAHIRAH WIDYANINGSIH',
            'LINGGA CAESARIO PRATAMA',
            'MUTIARA FEBRIANI',
            'NADINE AURELLIA LOPULALAN',
            'NAZWA ALYA RAUDATUL JANAH',
            'NOVITA ANGGRAINI HARIFRIANTO PUTRI',
            'NURUL FAUZIAH',
            'PANDU WIRA PUTRA',
            'RADEN CHALISTA ANINDYTA SOLEHA ACHDIAR',
            'RAIHANA BILBISYRI',
            'RISKA DESYA SAPUTRI',
            'SALSA AINUN',
            'THERESIA CLAUDIA RUMAYAR',

            // XII PPLG 1
            'ABDILLAH SYEH ABU BAKAR',
            'ABIGAIL MAKFIRA BUGIS SYAH',
            'AHMAD FADHILAH PRAMONO',
            'AHMAD FAUZAN MISBAKHUL ANAM',
            'AHMAD MUAMAR',
            'ANINDYA VIVIA PUTRI',
            'ARYA DWI RAHMAN',
            'ATHAILLAH NAZHIF FIRDAUS',
            'AULIA PUTRI SAKINAH',
            'DIMAS ABIMANYU',
            'FADEL KHAMARUZAMAN',
            'FADILAH RAMADAN',
            'FAHRA ADYA PUTRI',
            'FERDIAN DAFFAREL ARDIBRATA',
            'ILHAM MAULANA',
            'LOUDY FASYILKA HILAL AKBAR',
            'MUHAMAD ZAFAR SYAH',
            'MUHAMMAD AL BAGIR',
            'MUHAMMAD DHAFIN HARON',
            'MUHAMMAD FATHIR ALBANNY',
            'MUHAMMAD FATHIR RAMADHAN',
            'MUHAMMAD KEVIN',
            'NASHWA AYESHA PUTRI FEBRYANTO',
            'NIA RAHMADANI',
            'PUTRI MUSTIKA',
            'RAISYA HALSA FALAH',
            'RISKI DWI SAPUTRA',
            'RIVALDY RAMADHAN',
            'RIYANI',
            'SITI HUMAIRO AZZRA',
            'SULASTRI',
            'TASYA ERIKA',
            'TEDI SUBAGYONO',
            'TSABITA NASYATATIA RENATA',
            'UMI KULSUM',

            // XII PPLG 2
            'ABIYU RAYHAN',
            'ADESITA KARTINI LARASMIATI',
            'AL ZAHRA YUSLIA',
            'ALDY ANA JUANDENIES',
            'AMELIA PUTRI',
            'APRILIANI AYUNI ANOM',
            'ARYA PANCA PUTRA',
            'DHESWAN ANGGAR PRATAMA',
            'DIMAS ALWIANSYAH',
            'FADHIL HAYANG LAYANA',
            'FATIR ARDHANI',
            'GATOT KESUMA WARDANA',
            'ILHAM BINTANG',
            'INDRA DANI RAMADHAN',
            'IRFAN FIRMANSYAH',
            'KALEA IDZNI AULIA',
            'KESYA NUR AULIA',
            'KURNIA LESTARI',
            'M LUTHFI YOGA SUSANTO',
            'M. FAJAR SOVIANSYAH',
            'MAULIDIA',
            'MUHAMMAD AZREIL RAMADHAN',
            'MUHAMMAD FADLI RAMADHAN',
            'MUHAMMAD IBADILLAH DZIKRA',
            'MUHAMMAD ZEN ALHADI',
            'NAZWA ALIYA HIDAYAH',
            'NISA NURAINI',
            'NOVAL TRI SAKTI',
            'NUR ASIAH',
            'OKTAFIA ABEL SYAHPUTRI',
            'RAFI ATHARIANDO PUTRA',
            'RASYA NOUVAL NUGRAHA',
            'REZA AZMI SIRAJUDDIN',
            'THALITHA NURUL AQSA',
            'UMAR MUKHTAR',
            'ZAKY YASAR RAIHAN',

            // XII DKV 1
            'AINAH',
            'AMANDA SOFIA RACHMAH',
            'AMMAR SYAFIQ',
            'ANANDA FARREL DIMITRI',
            'ANDHIKA PUTRA TRIYANSYAH',
            'ANINDYARA SITI ANJANI',
            'AURHEL ALANA TIRTA',
            'CINDY AULIA KIRANA',
            'DEMI AURELYA FEBRIANDIKA',
            'DENDY PRASETYO',
            'DEWI NURROFIAH',
            'FADLY PUTRA BAHAWAN',
            'FEBI DWI APRIYANTI',
            'FUTRI RAHMAYANTI',
            'HANIF ADINUGRAHA',
            'HANIFATI SA\'ADAH MAULIDYA',
            'IBNATY SALSABILA ACHNES',
            'INDAH SAFITRI',
            'KAUTSAR ALI RAMADHAN',
            'KAYLA MAHARANI',
            'MUHAMAD HAFIZH SYAFIQ',
            'MUHAMAD RIFAN',
            'MUHAMMAD ADRIAN ISMI PUTRA',
            'MUHAMMAD ILHAM RAMADAN',
            'MUHAMMAD RAFFY PAMUNGKAS',
            'MUHAMMAD RIZKY',
            'NADINE CHESI OLIVIEN',
            'NIHA SAFWARNI TANZILA',
            'RAFA PUTRI AULIA',
            'RAFI ARYA NOVENDRA',
            'RIANTY RAMADHANI SYAPUTRI R',
            'RIDHA SYIFA AULIA',
            'SIRRAJAN GEMA RAMADHAN',
            'SUCI GAYATRI',
            'WIDYA ALFARINI',
            'YOPI NOVIANA',

            // XII DKV 2
            'ADINDA CHAIRRUNNISA',
            'ANGGITA RAHMAN',
            'ARIF TRI FADILLAH',
            'ARYA PUTRA RAMADHAN',
            'ATHYLA RAMADHAN',
            'AWAL AGUNG RAMADANI SIRAIT',
            'CHRIS RAFAEL ARUAN',
            'DANNY PRAKOSO WIDODO',
            'DAVA RIZKY FADILLAH',
            'DAVID RAJA MAIKEL SIMARMATA',
            'DINDA PUTRI RANIA',
            'ELLYSA PUJI LESTARI',
            'FAIRUZ ZAIN',
            'FATHIR RIZIQ RAHADI',
            'FIRSAN ABDIE RAHMAN',
            'GANDISLILIAN SUWONO',
            'GUSTI MUHAMAD ZICO RIFALDI',
            'ICA',
            'INTAN SURYA NATASYA',
            'JENNI NURHADIJAH',
            'MILHA AFIFAH YANI',
            'MOCHAMMAD DZAKY',
            'MUHAMMAD GALANG AL FATZ',
            'MUHAMMAD LUKMAN RAMDANI',
            'MUHAMMAD RIZKY',
            'NAILAH SALSABILA',
            'NURHIKMAH',
            'PATIMAH',
            'RAKA FAHDIL AFRIZAL',
            'SALSYA BILLAH RAHMADANIA',
            'SASKIA DAMAYANTI',
            'SHAYNA ESTELLA',
            'SITI NAYLA AHFINA',
            'SITI WARDIAH',
            'TIARA ASHITA SHANDYANI',

            // XII BCF 1
            'AHMAD FACHRUDDIN',
            'AKMAL FAUZAN',
            'ALDO FAJAR SAPUTRA',
            'ANINDYA WIDYADHANA KUSUMA',
            'ARFI ADISTI PRATAMA',
            'DAHLIA NUR ALAWIYAH',
            'GABRIELLA LIE',
            'LARAS AGUSTIN',
            'LIVIA AGUSTINA MARDIA',
            'MEYLANI',
            'MUHAMAD FIKRI JANUAR',
            'MUHAMAD ZULFI SETIAWAN',
            'MUHAMMAD DESTA ADITYA',
            'MUZHAFFIRA NAILA',
            'NABILLA NAJLA ULAYA',
            'NIR JAGAD SETIAWAN',
            'PRADIKA DWI PAMUNGKAS',
            'PRISCILLA FIONA NUGRAHA',
            'RENO DWI SAPUTRO',
            'REZA ARDHIANSYAH',
            'RIYANA JULYANTI',
            'SALWA NURAINI',
            'SARAH MAHYA ZAIDA',
            'SATRIA HALDAKKA RAMADHAN',
            'SEFTIAN ANDRIANSYAH',
            'SELLA PRATIWI',
            'SITI FAUZIAH',
            'SITI MAULA',
            'SULISTIYO H',
            'SYAQINA ANNISA SALSABILA',
            'SYIFA FAUZIYA AMANDA',
            'TANIA KHARIDAH MAHDIYAH',
            'WIDYA DWI HARYANI',
            'ZAHWA AULIA SOPA WAHAB',

            // XII BCF 2
            'AGUS RAFLI',
            'AMALIA NURAHMAWATI',
            'AYUDYA AZZAHRA EFFENDI',
            'BINTANG RAMADANY',
            'BUNGA GADIS ANANDYNA',
            'CAHAYA LINTANG FITRIAH',
            'DIMAS SEPTIYAN',
            'EVANDRA AHMAD SAPUTRA',
            'FARAH SYAKIRA',
            'IKI HERLIANA',
            'KAYLA AZZAHWA RIZKIKA',
            'MAUDY SALSABILA',
            'MAULIN ZAHRA',
            'MUHAMAD IQBAL TAWAKAL',
            'MUHAMMAD REZA SAPUTRA',
            'NAVARRA CAHYA KIRANI',
            'NILA KHOIRUN NAIL',
            'NUR YULIA AMARA',
            'RAFLY AHMAD SATRIAWAN',
            'REINDY ROZZAQ',
            'RISMA SUCI RAMADANIA',
            'SAMUEL HOTMIAN SILALAHI',
            'SAPHA TASYA KAMILA',
            'SHARMA HANDAYANI',
            'SHINTA TRI DAMAYANTI',
            'SITI MAULI',
            'SUCI OCTAVIANI DEWI',
            'SYAHRUL OCTA RAMADHAN',
            'TRI WULANDARI',
            'UDAY YUNUS',
            'YASMIN FAHIRA MARYAM',
            'ZAHRAH DWI FERNANDA',
            'ZHESYA REVINA SEPTRIANA',

            // XIII BCF
            'ADAM KHADAFI',
            'ADINDA PUTRI MARWAH',
            'ALYAA AFRAA AMAANDA',
            'AMELIA PRIHATINA',
            'AMELIA PUTRI LESTARI',
            'ANDINI ASYIFAH AINUN FIRDAUS',
            'ANISA AL FADILLAH',
            'APRILIA DWI PUTRI',
            'AYU NIMAS ARIFAH ZAHARANI S',
            'CHRISTOPER ELANG WIBISONO',
            'DEDE MAYA HASANAH',
            'DINDA RAHMA AULIA KHAIRUNISA',
            'FAHYU IRIA DARMAWAN',
            'FELLA ATTAQI BERLIAN',
            'GINA NAYLA',
            'IMELDA ZACKIA SAPNA',
            'INDAH KHUDAIFAH',
            'LEGISKA DEA SAPUTRI',
            'MUHAMMAD ARDAN ALFAREL',
            'NADILA PRADISTYA',
            'NIDA FAUZIANI',
            'NURFILDZAH AMALINA',
            'RADITYA AGRAFI',
            'RANI AGUSTIN',
            'RHAMADHANI FIRDAUS',
            'RISQIA PUTRI CAHYANI',
            'ROSMALA AINIYA',
            'SALAS PUTRA HERMAWAN',
            'SALSYAH DWI CAHYANINGTIAS',
            'SHEILA SALSABILA',
            'SITI ZAHRA AMELIA',
            'SYAHARANI ADELIA',
            'TESA ANGELICA OKTAVIA',
            'ZASKIA ISLAMI PUTRI',


            // GURU / PENGURUS SEKOLAH
            'Aty Triastuti',
            'Sri Murningsih',
            'Slamet Sukotjo',
            'Yati Supriyati',
            'Romauli Pakpahan',
            'Vilia Eka Meyana',
            'Mercy Sidabukke',
            'Nuryani Pringgo Sentiko',
            'Aang Setiadi',
            'Zaenudin',
            'Sri Arum Hartini',
            'Istiana Furih',
            'Nurhayati',
            'Ririn Riandhita',
            'Muthia Adenami',
            'Yuli Kurniawati',
            'Imam Farniawan',
            'Amelia Indah Bestari',
            'Abhy Sukma Pratama',
            'Muhammad Ridwan Patawari',
            'Heni Verawati',
            'Nurussyifa Fahriza',
            'Baasith Syahramdani',
            'Fenefrida Elmi Swantie',
            'Martia Aviva',
            'Ashari',
            'Budiman Akbar',



            // ADMIN ADMIN ADMIN
            'admin'


        ];



        $data = [];

        for ($i = 0; $i < count($nisList); $i++) {
            $data[] = [
                'password' => Hash::make($nisList[$i]),
                'nama' => $usernames[$i],
            ];
        }

        // Insert the data into the users table
        DB::table('users')->insert($data);
    }
}
